services:
  app:
    build: .
    container_name: property_rental_api
    expose:
      - "8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      SPRING_REFRESH_TOKEN_EXPIRE: 2592000000
      SPRING_ACCESS_TOKEN_EXPIRE: 900000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
    networks:
      - demo_proxy
      - proxy

networks:
  demo_proxy:
    external: true
    name: demo_proxy

  proxy:
    external: true
    name: proxy
