services:
  app:
    build: .
    container_name: property_rental_api
    expose:
      - "8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      SPRING_REFRESH_TOKEN_EXPIRE: ${SPRING_REFRESH_TOKEN_EXPIRE}
      SPRING_ACCESS_TOKEN_EXPIRE: ${SPRING_ACCESS_TOKEN_EXPIRE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
    networks:
      - demo_proxy
      - proxy

networks:
  demo_proxy:
    external: true
    name: demo_proxy

  proxy:
    external: true
    name: proxy
